config/routes.rb
Galleryten::Application.routes.draw do
  match 'gallery'     => 'static#gallery'
  match 'classroom'   => 'static#classroom'
  match 'studentwork' => 'static#studentwork'
  match 'about'       => 'static#about'
  match 'staff'       => 'static#staff'
  match 'contact'       => 'static#contact'

  root to: 'static#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def gallery
  end

  def classroom
  end

  def staff
  end

  def about
  end

  def studentwork
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_header-topbar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "ギャラリー天", root_path, class: 'brand' %>
      <div class="nav-collapse">
        <ul class="nav">
            <li><%= link_to "ホーム", root_path %></li>
            <li><%= link_to "ギャラリー天", about_path %></li>
            <li><%= link_to "陶芸教室", classroom_path %></li>
            <li><%= link_to "生徒作品紹介", studentwork_path %></li>
            <li><%= link_to "スタッフ", staff_path %></li>
            <li><%= link_to "貸しギャラリー", gallery_path %></li>
            <li><%= link_to "お問い合わせ", contact_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_sidemenu.html.erb
	<div class="span2">
      	<div class="well sidebar-nav">
            <ul class="nav nav-list">
              	<li class="nav-header">ナビゲーション</li>
              	<li><%= link_to "ホーム", root_path %></li>
              	<li><%= link_to "ギャラリー天", about_path %></li>
              	<li><%= link_to "陶芸教室", classroom_path %></li>
              	<li><%= link_to "生徒作品紹介", studentwork_path %></li>
              	<li><%= link_to "スタッフ", staff_path %></li>
              	<li><%= link_to "貸しギャラリー", gallery_path %></li>
              	<li><%= link_to "お問い合わせ", contact_path %></li>
            </ul>
         </div>
    </div>

app/views/layouts/_stylesheets.html.erb
<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
  <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

<!-- Le styles -->
<%= stylesheet_link_tag "bootstrap/bootstrap", media: 'all' %>
<style type="text/css">
  body {
    padding-top: 60px;
    padding-bottom: 40px;
  }
</style>
<%= stylesheet_link_tag "bootstrap/bootstrap-responsive", media: 'all' %>


<!-- Le fav and touch icons -->
<link rel="shortcut icon" href="images/favicon.ico">
<link rel="apple-touch-icon" href="images/apple-touch-icon.png">
<link rel="apple-touch-icon" sizes="72x72" href="images/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="114x114" href="images/apple-touch-icon-114x114.png">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>gallary ten</title>
    <meta name="description" content="">
    <meta name="author" content="">

    	<!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
		<%= render 'layouts/stylesheets' %>

		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>

	</head>
	<body>

		<%= render 'layouts/header-topbar' %>

		<div class="container">

			<div class="row">
				<div class="span4">
					<a href="https://twitter.com/share" class="twitter-share-button" data-text="Gallery Ten Tokyo" data-via="henjo">Tweet</a>
					<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");
					</script>
					<!-- google +1 -->
					<g:plusone size="medium"></g:plusone>
				</div>
			    <div class="span8">
					<p class="pull-right">03-5482-5245 | 〒146-0084 東京都大田区南久が原2-31-10</p>
				</div>
			</div>

			<%= yield %>

			<hr>

			<footer>
				<div class="row">
					<div class="span5">
						<form class="form-inline">
						    <fieldset>
						      <div class="control-group">
						        <label class="control-label" for="input01_email">ニュースレター登録申し込み：</label>
						        <div class="controls">
						          <input type="text" class="input-xlarge" id="input01_email">
						          <button type="submit" class="btn-primary">送信</button>
						        </div>
						      </div>
						    </fieldset>
						</form>
						<p>&copy; Gallery Ten 2012</p>
					</div>
					<div class="span5 offset2">
						
					</div>
				</div>
			</footer>
		</div>

		<!-- google +1 render code -->
		<script type="text/javascript">
		  window.___gcfg = {lang: 'ja'};

		  (function() {
		    var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
		    po.src = 'https://apis.google.com/js/plusone.js';
		    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
		  })();
		</script>

	</body>
</html>